version: '3.7'

services:
  invoice:
    build: .
    networks:
      - api-net
    container_name: "python_flask_invoice"
    ports:
      # For flask default server use 5001:5000
      - 8002:8000
    # volumes:
      # Mount current directory from docker host to /usr/src/app in container
      # - .:/usr/src/app
    restart: always

networks:
  api-net:
    external:
      name: python-flask-app-network