version: '3.7'

services:
  nginx:
    image: nginx:latest
    container_name: "python_flask_home_nginx"
    depends_on:
      - web
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
  web:
    # This directory should have Dockerfile
    build: .
    networks:
      - default
    container_name: "python_flask_home_web"
    ports:
      # For flask default server use 5001:5000
      - 8000:8000
    volumes:
      # Mount current directory from docker host to /usr/src/app in container
      - .:/usr/src/app
    restart: always