# Used for creating service and integrating with deployment
# kubectl create -f home-service.yml
apiVersion: v1
kind: Service
metadata:
  name: home
spec:
  selector:
    app: home
  ports:
  - protocol: "TCP"
    port: 8001
    name: http-home
    targetPort: 8000
  # Set this as NodePort for accessing outside in env without LoadBalancer
  type: ClusterIP
