# Used for Deployment
# kubectl apply -f home-deployment.yml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: home
spec:
  selector:
    matchLabels:
      app: home
  replicas: 1
  template:
    metadata:
      labels:
        app: home
    spec:
      containers:
      - name: home
        image: rakeshagrawal1502/python-flask-home:1.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        # command: ["/bin/sh", "-ec", "while :; do echo '.'; sleep 5 ; done"]
