# Used for creating service and integrating with deployment
# kubectl create -f .\home-service.yml
apiVersion: v1
kind: Service
metadata:
  name: home
spec:
  selector:
    app: home
  ports:
  - protocol: "TCP"
    port: 8001
    targetPort: 8000
  type: LoadBalancer