# The binding between a Pod and PersistentVolume
# kubectl apply -f persistent-volume-claim.yml
# kubectl get pvc
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: postgres
  name: postgres-pvc
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100M