# Secrets are used to handle sensitive info such as passwords, API tokens, and SSH keys.

# rakesh_agrawal@HSL014875 MINGW64 ~
# $ echo -n "postgres" | base64
# cG9zdGdyZXM=

# rakesh_agrawal@HSL014875 MINGW64 ~
# $ echo -n "password" | base64
# cGFzc3dvcmQ=

# kubectl apply -f secret.yml
# kubectl get secrets

apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
data:
  user: cG9zdGdyZXM=
  password: cGFzc3dvcmQ=
