# Used for creating service and integrating with deployment
# kubectl create -f .\nginx-service.yml

apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  ports:
  - protocol: "TCP"
    port: 80
    name: http-nginx
    targetPort: 80
  type: LoadBalancer
