# Used for Deployment
# kubectl apply -f .\nginx-deployment.yml

# Put the nginx config file in configmap so that later it can be used from deployment yaml file to put the
# config file in containers
# kubectl create configmap nginx-config --from-file nginx.conf
# kubectl get configmaps

# We can also keep nginx conf as part of configmap yaml. To generate Yaml from command we can use below command:
# kubectl create configmap --dry-run test-config --from-file nginx.conf --output yaml > test-configmap.yml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        volumeMounts:
          - name: nginx-config
            mountPath: /etc/nginx/conf.d
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
