# Used for creating service and integrating with deployment
# kubectl create -f .\customer-service.yml
# port: port at which the service may be reached at
# targetPort: port on which the service’s corresponding container receives traffic at
apiVersion: v1
kind: Service
metadata:
  name: customer
spec:
  selector:
    app: customer
  ports:
  - protocol: "TCP"
    port: 8000
    name: http-customer
    targetPort: 8000
  type: ClusterIP
